// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEo9sz9VAd8VXOUOifLJczX5wlBN3BqLM',
    appId: '1:963721959947:web:cd4ce3536f20344dd1450e',
    messagingSenderId: '963721959947',
    projectId: 'my-community-dd399',
    authDomain: 'my-community-dd399.firebaseapp.com',
    storageBucket: 'my-community-dd399.appspot.com',
    measurementId: 'G-7BYW8DF5BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADelcbGWtqUzavxPXtAAZ7Jyr7t1Lma9A',
    appId: '1:963721959947:android:826cae98cca240bdd1450e',
    messagingSenderId: '963721959947',
    projectId: 'my-community-dd399',
    storageBucket: 'my-community-dd399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBaW9F1KzXJs5xfGNMlF_iDdCowzvut1U',
    appId: '1:963721959947:ios:3baa1dc79b99b482d1450e',
    messagingSenderId: '963721959947',
    projectId: 'my-community-dd399',
    storageBucket: 'my-community-dd399.appspot.com',
    iosBundleId: 'com.example.modul7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBaW9F1KzXJs5xfGNMlF_iDdCowzvut1U',
    appId: '1:963721959947:ios:c462acef9fd7964cd1450e',
    messagingSenderId: '963721959947',
    projectId: 'my-community-dd399',
    storageBucket: 'my-community-dd399.appspot.com',
    iosBundleId: 'com.example.modul7.RunnerTests',
  );
}
